schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "CurveFitting"
version = "0.2.1"
name = "Curve Fitting"
tagline = "Smooth out uneven vertex arrangements keeping original shape"
maintainer = "zuda77"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/zuda77/CurveFitting_blender_addon/"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Mesh", "Modeling"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

# [permissions]
# None


#[build]
#paths_exclude_pattern = [
#  ".git/",
#  "__pycache__/",
#  "resource/",
#  "*.gitignore",
#]
